### ISSUE TITLE
Update Hanging.

### ISSUE THREAD

**Issue by appfollower** [jt70471/InkjetPlumber#10]
<img width="464" alt="screen shot 2016-08-03 at 1 15 04 pm" src="https://cloud.githubusercontent.com/assets/20591358/17380804/c172a6fc-597d-11e6-8d10-baebe06c6eda.png">

**Comment by jt70471** [comment]
Hi, the server hosting the updates is down at present. Hopefully that will be resolved soon but I am out of town until Friday and can't access the server remotely, so it may be a few more days unfortunately.

**Comment by jt70471** [comment]
Looks like the server is back up. If you can confirm, I'll close this one. Thanks!

**Comment by appfollower** [comment]
OK, it's working.
