### ISSUE TITLE
Is it possible to set certain time to start?

### ISSUE THREAD

**Issue by yuickey** [jt70471/InkjetPlumber#15]
I would like it to run 3am and run it everyday, then I need to wait until 3 am to set..
Is there any way to modify time?

**Comment by HeckFinlay** [comment]
This would be my number one feature request.

**Comment by jt70471** [comment]
There's currently no way to do this via the user interface, nor will I be able to add since I'm not actively developing InkjetPlumber. You can use something like Qimage One which is supported commercial software instead. Regards.
