### ISSUE TITLE
epson XP7100 fails to print

### ISSUE THREAD

**Issue by davidgue2** [jt70471/InkjetPlumber#18]
using Mac release 0.9.15. on OS 13.5.2 using either USB and wireless printer connection. 

Wireless gives error:E [09/Nov/2023:13:46:10 -0700] [Client 65] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/EPSON_XP_7100_Series) from localhost.

USB gives error E [09/Nov/2023:13:35:49 -0700] [Client 47] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/EPSON_XP_7100_USB) from localhost.

**Comment by jt70471** [comment]
Sorry you're having issues. Unfortunately I'm no longer able to support InkjetPlumber. The premise that using something like InkjetPlumber to avoid printer cleaning cycles has been proven to be false. Today, I use Qimage One to exercise my printers periodically. You may want to look at Qimage One or another tool if available.

**Comment by davidgue2** [comment]
Thanks for the quick response, and sorry that Inkjet Plumber ends up as an excellent tool for a job that isn’t needed. Such is life ….DGOn Nov 14, 2023, at 1:29 PM, Jeff Thompson ***@***.***> wrote:﻿
Sorry you're having issues. Unfortunately I'm no longer able to support InkjetPlumber. The premise that using something like InkjetPlumber to avoid printer cleaning cycles has been proven to be false. Today, I use Qimage One to exercise my printers periodically. You may want to look at Qimage One or another tool if available.
