### ISSUE TITLE
No Auto Print on Schedule

### ISSUE THREAD

**Issue by appfollower** [jt70471/InkjetPlumber#4]
The auto generated print page was not generated on schedule (12 hours from initial install of program) for either of my printers. As soon as I opened the app, the print page then generated for each of the printers. Should I leave the app open all the time? I was thinking it would open itself on the assigned schedule and print the pages. Also, as you probably know, the color squares on the printed pages are still at 1/8th inch square with the numbers offset.

Could you email me at:
russcolban@yahoo.com     
and let me know if I should leave the app open? I'm not sure what the protocol is for this website. Thanks,
Russ
iMac  ElCapitan  Canon Pixma Pro100  Brother MFC490CW

**Comment by jt70471** [comment]
Russ, I'll email you as requested, but just a few quick responses:

1. Yes, the app needs to be running to print at the interval you specify, so you should just minimize it and it should run in the background printing the maintenance job every X hours that you specified.

2. I think I have solved the small color swatch issue in version 0.9.1.2. If you haven't upgraded to that version yet, please do so by selecting the "Check for Updates..." menu item.
