### ISSUE TITLE
This Window Opens When Click on Menu Bar Icon

### ISSUE THREAD

**Issue by appfollower** [jt70471/InkjetPlumber#7]
Jeff, I'm sure you know this, but I wanted to make sure you're aware this window opens when I open the program.

<img width="804" alt="screen shot 2016-07-25 at 11 01 36 pm" src="https://cloud.githubusercontent.com/assets/20591358/17127655/237b1f46-52bc-11e6-92ca-7b3d7bf45acb.png">

**Comment by jt70471** [comment]
Russ, yes, that window is the main window of the application, it will show when you start the app and hide when you click on the red (close) button or the yellow (minimize) buttons in the top left of the window.

It will remain hidden until you click on one of the menuBar menu items, which will cause it to show itself again, etc.
