### ISSUE TITLE
Icon doesn't show correctly in dark menu bar

### ISSUE THREAD

**Issue by giubeppe** [jt70471/InkjetPlumber#9]
As in subject. The menu bar icon seems to be designed for bright menu bar and it displays only an outline when dark menu interface is selected.

**Comment by jt70471** [comment]
Hi, I'll have to look into how to handle this. For now, you'll have to either live with the issue or choose to not use the dark menubar setting for your Mac.

I'll leave this open until I have a workaround or permanent fix. Thanks.
